Repository UniversalViewer/universalviewer, pull requests merged in 2024-10, with the labels that each got.

#905 Upgrading to Openseadragon v4
  package-lock.json
  package.json
Labels: steering group review

#1135 Make hidden skip link visible on focus (fixes #1088)
  src/content-handlers/iiif/modules/uv-shared-module/css/scaffolding.less
Labels: accessibility, accessibility-keyboard

#1134 Remove hard-coded text from infobox label.
  src/content-handlers/iiif/modules/uv-shared-module/HeaderPanel.ts
Labels: accessibility, accessibility-label

#1182 Update @iiif/iiif-gallery-component to v1.1.22.
  package-lock.json
  package.json
Labels: accessibility, accessibility-keyboard
